[package]
name = "mock_device"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
reqwest = { version = "0.12.2", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.1" 